spring:
  application:
    name: Shopping
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456

  mvc:
    cors:
      allowed-origins: "http://localhost:8080"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8088
